package com.dpzx.route_compiler;

/**
 * Create by xuqunxing on  2020/10/14
 */
public class consts {
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "Router";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String IROUTE_PACKAGE = "com.dpzx.route_compiler";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.dpzx.smartrouter.routes";
    public static final String PACKAGE = "com.nsyw.routerdemo";
    public static final String TEMPLATE_PACKAGE = ".template";
    public static final String IROUTE = IROUTE_PACKAGE + ".IRoute";
    public static final String NAME_OF_ROUTE = PROJECT + SEPARATOR + "App"+SEPARATOR;
    public static final String KEY_MODULE_NAME = "ROUTER_MODULE_NAME";
    public static final String ACTIVITY = "android.app.Activity";


    public static final String ANN_TYPE_ROUTE = "com.dpzx.route_compiler.anotation.Route";
}